In [1]:
# add signal information to existing Lima GMNS network created by DynusT_to_GMNS.R
import numpy as np
import pandas as pd
import os, shutil

In [2]:
# load network files that need to bie modified 
nodes = pd.read_csv('../../../examples/Lima/GMNS/node.csv')
links = pd.read_csv('../../../examples/Lima/GMNS/link.csv')
mvmts = pd.read_csv('../../../examples/Lima/GMNS/movement.csv')

In [3]:
# parse control.dat
f = open('../../../examples/Lima/source_network/control.dat', 'r')

In [4]:
# first line - number of timing plans
n_timePlans = int(f.readline())

In [5]:
timePlan_info = []
i = 0
while i < n_timePlans:
    timePlan_info.append(f.readline())
    i = i + 1
    
#TODO parse timePlan info
# Lima only has one, so handling manually for now

In [6]:
# node info
len(nodes)

2232

In [7]:
node_cols = {
    0: "node_id",
    1: "ctrl_type",
    2: "num_phases",
    3: "cycle_time"
}

phase_key = {
    1: "none",
    2: "yield",
    3: "4_stop",
    4: "signal",
    5: "signal",
    6: "2_stop"
}

In [8]:
rows = []
i = 0
while i < len(nodes):
    row = pd.Series(f.readline().split()).astype(int).rename(node_cols).astype('object')
    row['ctrl_type'] = phase_key[row['ctrl_type']]
    rows.append(row)
    i = i + 1

ctrl_nodes = pd.DataFrame(rows)

In [9]:
sig_node_ct = len(ctrl_nodes[ctrl_nodes['ctrl_type'] == 'signal'])

i = 0
k = 0 
node_phase_lines = []
link_phase_lines = []
while i < sig_node_ct:
    # get first phase
    node_phase_line = f.readline()
    node_phase_lines.append(node_phase_line)
    # get num of phases assoc with that node
    node_id = int(node_phase_line.split()[0])
    node_phase_ct = int(ctrl_nodes[ctrl_nodes['node_id'] == node_id]['num_phases'].iloc[0])
    j = 0 
    inbound_link_ct = int(node_phase_line.split()[5])
    while j < inbound_link_ct:
        link_phase_line = f.readline()
        link_phase_lines.append(link_phase_line)
        j = j + 1
    k = k + 1
    if k >= node_phase_ct:
        i = i + 1
        k = 0

# TODO process into dfs

In [10]:
# skip next line "=======Two Way Stop Signs/Yield Signs Below ======="
f.readline()

'=======Two Way Stop Signs/Yield Signs Below =======\n'

In [11]:
# remainder is two-way stop/yield info
twoway_temp = f.readlines()

In [12]:
# EOF
f.close()

In [13]:
temp_df = pd.DataFrame([pd.Series(i.split()) for i in twoway_temp if twoway_temp.index(i) % 3 == 1]).astype('Int64')
temp_df

          0       1       2       3       4       5       6       7
0    100018  100019  100093  100019  100020  100019    <NA>    <NA>
1    100041  100040  100039  100040  100280  100040    <NA>    <NA>
2    100068  100069  100070  100069  100062  100069  100073  100069
3    100070  100071  100086  100071  100061  100071  100072  100071
4    100088  100086  100082  100086  100099  100086  100071  100086
..      ...     ...     ...     ...     ...     ...     ...     ...
173  104280  104286  104192  104286  104173  104286  103852  104286
174  104181  104322  104319  104322  104176  104322  104327  104322
175  104198  104327  104328  104327  104322  104327  104002  104327
176  104343  104339  103516  104339  104350  104339  104338  104339
177  103529  104402  104412  104402  103513  104402  104404  104402

[178 rows x 8 columns]

In [14]:
links_twowaystop = pd.lreshape(temp_df, {'start_node': temp_df.columns[temp_df.columns % 2 == 0], 'end_node': temp_df.columns[temp_df.columns % 2 == 1]})
links_twowaystop

     start_node  end_node
0        100018    100019
1        100041    100040
2        100068    100069
3        100070    100071
4        100088    100086
..          ...       ...
675      103852    104286
676      104327    104322
677      104002    104327
678      104338    104339
679      104404    104402

[680 rows x 2 columns]

In [15]:
## now modify the existing gmns tables

In [16]:
nodes['ctrl_type'] = nodes.merge(ctrl_nodes, on = 'node_id')['ctrl_type_y']
nodes

,node_id,name,x_coord,y_coord,z_coord,node_type,ctrl_type,zone_id,parent_node_id
0,1,NaN,1523373.000,1003235.000,NaN,NaN,none,1,NaN
1,2,NaN,1523873.000,1003225.000,NaN,NaN,none,2,NaN
2,3,NaN,1524263.000,1003205.000,NaN,NaN,none,3,NaN
3,4,NaN,1524224.000,1002265.000,NaN,NaN,none,4,NaN
4,5,NaN,1523854.000,1002765.000,NaN,NaN,none,5,NaN
...,...,...,...,...,...,...,...,...,...
2227,104443,NaN,1531243.411,993559.625,NaN,NaN,none,62,NaN
2228,104444,NaN,1532299.387,993452.125,NaN,NaN,none,69,NaN
2229,104445,NaN,1507167.100,995978.919,NaN,NaN,signal,120,NaN
2230,104446,NaN,1507084.155,999960.306,NaN,NaN,none,192,NaN
2231,104447,NaN,1507167.100,995336.091,NaN,NaN,none,120,NaN

In [17]:
# get control type for these -- two-way stop vs yield
# in Lima's case, it's all 2ways, no yields
links_twowaystop = links_twowaystop.merge(ctrl_nodes[['node_id', 'ctrl_type']], left_on='end_node', right_on='node_id')

In [18]:
# applying control types to movements
# generally, inherit ctrl_type of node
# except two-way stop/yield: use 'none' unless in links_twowaystop list

mvmts['ctrl_type'] = mvmts.merge(ctrl_nodes, on='node_id')['ctrl_type_y']
mvmts

,mvmt_id,node_id,name,ib_link_id,start_ib_lane,end_ib_lane,ob_link_id,start_ob_lane,end_ob_lane,type,penalty,capacity,ctrl_type
0,1,1,NaN,100002 1,1.0,1.0,1 100002,1.0,1.0,uturn,NaN,NaN,none
1,2,1,NaN,101990 1,1.0,1.0,1 101990,1.0,1.0,uturn,NaN,NaN,none
2,3,1,NaN,101997 1,1.0,1.0,1 101997,1.0,1.0,uturn,NaN,NaN,none
3,4,1,NaN,101998 1,1.0,1.0,1 101998,1.0,1.0,uturn,NaN,NaN,none
4,5,2,NaN,100004 2,1.0,1.0,2 100004,1.0,1.0,uturn,NaN,NaN,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12622,12623,104446,NaN,100739 104446,2.0,2.0,104446 192,1.0,1.0,right,NaN,NaN,none
12623,12624,104446,NaN,104445 104446,2.0,2.0,104446 118,1.0,1.0,right,NaN,NaN,none
12624,12625,104447,NaN,120 104447,1.0,1.0,104447 104445,1.0,1.0,thru,NaN,NaN,none
12625,12626,104447,NaN,104445 104447,1.0,1.0,104447 120,1.0,1.0,thru,NaN,NaN,none
12626,12627,104447,NaN,104445 104447,1.0,1.0,104447 104445,1.0,1.0,uturn,NaN,NaN,none

In [19]:
links_twowaystop['link_id'] = links_twowaystop['start_node'].astype(str) + " " + links_twowaystop['end_node'].astype(str)
links_twowaystop

     start_node  end_node  node_id ctrl_type        link_id
0        100018    100019   100019    2_stop  100018 100019
1        100041    100040   100040    2_stop  100041 100040
2        100068    100069   100069    2_stop  100068 100069
3        100070    100071   100071    2_stop  100070 100071
4        100088    100086   100086    2_stop  100088 100086
..          ...       ...      ...       ...            ...
675      103852    104286   104286    2_stop  103852 104286
676      104327    104322   104322    2_stop  104327 104322
677      104002    104327   104327    2_stop  104002 104327
678      104338    104339   104339    2_stop  104338 104339
679      104404    104402   104402    2_stop  104404 104402

[680 rows x 5 columns]

In [20]:
# Lima dataset error: all links inbound to a two-way stop controlled intersection seem to be tagged as stop-controlled
# This is an empty df subset but normally would want to replace the ctrl_type of this list to be 'none'
mvmts[(~mvmts['ib_link_id'].isin(links_twowaystop['link_id'])) & (mvmts['node_id'].isin(ctrl_nodes[ctrl_nodes['ctrl_type'] == '2_stop']['node_id']))]

Empty DataFrame
Columns: [mvmt_id, node_id, name, ib_link_id, start_ib_lane, end_ib_lane, ob_link_id, start_ob_lane, end_ob_lane, type, penalty, capacity, ctrl_type]
Index: []

In [21]:
# fix dtype of lanes
mvmts[[c for c in mvmts.columns if 'b_lane' in c]] = mvmts[[c for c in mvmts.columns if 'b_lane' in c]].astype('Int64')

In [22]:
# export current changes
nodes.to_csv('../../../examples/Lima/GMNS/node.csv', index=False)
links.to_csv('../../../examples/Lima/GMNS/link.csv', index=False)
mvmts.to_csv('../../../examples/Lima/GMNS/movement.csv', index=False)

In [22]:
ctrl_nodes[ctrl_nodes['ctrl_type'] == 'signal']

      node_id ctrl_type  num_phases  cycle_time
449    100000    signal           2         188
450    100001    signal           2         188
452    100003    signal           3         226
455    100006    signal           2         188
459    100010    signal           2         188
...       ...       ...         ...         ...
2121   104313    signal           2         190
2125   104317    signal           2         190
2174   104373    signal           2         190
2196   104408    signal           2         190
2229   104445    signal           2         130

[165 rows x 4 columns]

In [23]:
## now create the new signal tables from node_phase_lines and link_phase_lines
# no coordination, one timing plan per controller simplifies things columns=["controller_id"]

signal_controllers = pd.DataFrame(ctrl_nodes[ctrl_nodes['ctrl_type'] == 'signal']['node_id']).rename(columns={"node_id": "controller_id"}).reset_index(drop=True)
signal_controllers

     controller_id
0           100000
1           100001
2           100003
3           100006
4           100010
..             ...
160         104313
161         104317
162         104373
163         104408
164         104445

[165 rows x 1 columns]

In [24]:
# read as "timing plan 0 starts at 1740" (but what units??)
# not worrying about it for now because every controller in Lima data has one timing plan
timePlan_info

['    0.0 1740.0\n']

In [25]:
signal_timing_plans = pd.DataFrame(ctrl_nodes[ctrl_nodes['ctrl_type'] == 'signal'][['node_id', 'cycle_time']])
signal_timing_plans = signal_timing_plans.rename(columns = {'node_id': 'timing_plan_id', 'cycle_time': 'cycle_length'})
signal_timing_plans['controller_id'] = signal_timing_plans['timing_plan_id']
signal_timing_plans['cycle_length'] = signal_timing_plans['cycle_length']
signal_timing_plans['timeday_id'] = np.nan
signal_timing_plans['time_day'] = '11111111_0000_2359'

signal_timing_plans = signal_timing_plans.reset_index(drop=True)
signal_timing_plans

,timing_plan_id,cycle_length,controller_id,timeday_id,time_day
0,100000,188,100000,NaN,11111111_0000_2359
1,100001,188,100001,NaN,11111111_0000_2359
2,100003,226,100003,NaN,11111111_0000_2359
3,100006,188,100006,NaN,11111111_0000_2359
4,100010,188,100010,NaN,11111111_0000_2359
...,...,...,...,...,...
160,104313,190,104313,NaN,11111111_0000_2359
161,104317,190,104317,NaN,11111111_0000_2359
162,104373,190,104373,NaN,11111111_0000_2359
163,104408,190,104408,NaN,11111111_0000_2359
164,104445,130,104445,NaN,11111111_0000_2359

In [26]:
node_phase_index = [
    "timing_plan_id",
    "signal_phase_num",
    "max_green", # "offset" if type 4 but all are type 5
    "min_green",
    "clearance", # yellow time (no all red)
    "inbound_link_ct",
    "ib_node1",
    "ib_node2",
    "ib_node3",
    "ib_node4"
]

In [77]:
signal_timing_phase = pd.DataFrame([pd.Series(i.split(), index = node_phase_index).astype(int) for i in node_phase_lines])
signal_timing_phase = signal_timing_phase.drop(columns=[ "inbound_link_ct", "ib_node1", "ib_node2", "ib_node3", "ib_node4"])

In [78]:
empty_columns = ['extension', 'walk_time', 'ped_clearance', 'ring', 'barrier', 'position']
for col in empty_columns:
    signal_timing_phase[col] = pd.Series()
    
signal_timing_phase['timing_phase_id'] = (signal_timing_phase['timing_plan_id'] * 100) + signal_timing_phase['signal_phase_num']
signal_timing_phase

,timing_plan_id,signal_phase_num,max_green,min_green,clearance,extension,walk_time,ped_clearance,ring,barrier,position,timing_phase_id
0,100000,1,90,15,4,NaN,NaN,NaN,NaN,NaN,NaN,10000001
1,100000,2,90,15,4,NaN,NaN,NaN,NaN,NaN,NaN,10000002
2,100001,1,90,15,4,NaN,NaN,NaN,NaN,NaN,NaN,10000101
3,100001,2,90,15,4,NaN,NaN,NaN,NaN,NaN,NaN,10000102
4,100003,1,40,5,2,NaN,NaN,NaN,NaN,NaN,NaN,10000301
...,...,...,...,...,...,...,...,...,...,...,...,...
433,104373,2,90,20,5,NaN,NaN,NaN,NaN,NaN,NaN,10437302
434,104408,1,90,25,5,NaN,NaN,NaN,NaN,NaN,NaN,10440801
435,104408,2,90,20,5,NaN,NaN,NaN,NaN,NaN,NaN,10440802
436,104445,1,60,5,5,NaN,NaN,NaN,NaN,NaN,NaN,10444501
437,104445,2,60,5,5,NaN,NaN,NaN,NaN,NaN,NaN,10444502

In [32]:
signal_timing_phase = signal_timing_phase[["timing_phase_id","timing_plan_id","signal_phase_num","min_green","max_green","extension","clearance","walk_time","ped_clearance","ring","barrier","position"]]

In [30]:
# signal_phase_mvmt
# get ib_link and ob_link from link_phase_line
# find corresponding movement(s)
temp_df = pd.DataFrame([pd.Series(i.split()) for i in link_phase_lines])
temp_df

          0       1  2  3       4       5       6       7
0    100001  100000  1  2  100289  100283     NaN     NaN
1    100283  100000  1  2  100001  100289     NaN     NaN
2    100284  100000  2  3  100001  100289  100283     NaN
3    100000  100001  1  2  101998  100002     NaN     NaN
4    100002  100001  1  2  100000  101998     NaN     NaN
..      ...     ... .. ..     ...     ...     ...     ...
816  104410  104408  2  4  103566  104409  100756  104410
817  100565  104445  1  3  104447  100564  104446     NaN
818  100564  104445  1  3  104446  100565  104447     NaN
819  104447  104445  2  4  100564  104446  100565  104447
820  104446  104445  2  3  100565  104447  100564     NaN

[821 rows x 8 columns]

In [31]:
temp_df['ib_link_id'] = temp_df[0] + ' ' + temp_df[1]
temp_df['ob_link_id1'] = temp_df[1] + ' ' + temp_df[4]
temp_df['ob_link_id2'] = temp_df[1] + ' ' + temp_df[5]
temp_df['ob_link_id3'] = temp_df[1] + ' ' + temp_df[6]
temp_df['ob_link_id4'] = temp_df[1] + ' ' + temp_df[7]
temp_df['timing_phase_id'] = (temp_df[1].astype(int) * 100) + temp_df[2].astype(int)
temp_df

,0,1,2,3,4,5,6,7,ib_link_id,ob_link_id1,ob_link_id2,ob_link_id3,ob_link_id4,timing_phase_id
0,100001,100000,1,2,100289,100283,NaN,NaN,100001 100000,100000 100289,100000 100283,NaN,NaN,10000001
1,100283,100000,1,2,100001,100289,NaN,NaN,100283 100000,100000 100001,100000 100289,NaN,NaN,10000001
2,100284,100000,2,3,100001,100289,100283,NaN,100284 100000,100000 100001,100000 100289,100000 100283,NaN,10000002
3,100000,100001,1,2,101998,100002,NaN,NaN,100000 100001,100001 101998,100001 100002,NaN,NaN,10000101
4,100002,100001,1,2,100000,101998,NaN,NaN,100002 100001,100001 100000,100001 101998,NaN,NaN,10000101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,104410,104408,2,4,103566,104409,100756,104410,104410 104408,104408 103566,104408 104409,104408 100756,104408 104410,10440802
817,100565,104445,1,3,104447,100564,104446,NaN,100565 104445,104445 104447,104445 100564,104445 104446,NaN,10444501
818,100564,104445,1,3,104446,100565,104447,NaN,100564 104445,104445 104446,104445 100565,104445 104447,NaN,10444501
819,104447,104445,2,4,100564,104446,100565,104447,104447 104445,104445 100564,104445 104446,104445 100565,104445 104447,10444502
820,104446,104445,2,3,100565,104447,100564,NaN,104446 104445,104445 100565,104445 104447,104445 100564,NaN,10444502

In [37]:
mvmt_join_df = pd.lreshape(temp_df, {"ib_link_id": ["ib_link_id","ib_link_id","ib_link_id","ib_link_id"], 
                            "ob_link_id": ['ob_link_id1','ob_link_id2','ob_link_id3','ob_link_id4'],
                            "timing_phase_id": ["timing_phase_id","timing_phase_id","timing_phase_id","timing_phase_id"]
                           })
mvmt_join_df = mvmt_join_df.drop(columns=range(8))
mvmt_join_df

         ib_link_id     ob_link_id  timing_phase_id
0     100001 100000  100000 100289         10000001
1     100283 100000  100000 100001         10000001
2     100284 100000  100000 100001         10000002
3     100000 100001  100001 101998         10000101
4     100002 100001  100001 100000         10000101
...             ...            ...              ...
1966  100689 103812  103812 100689         10381201
1967  100683 103812  103812 100683         10381202
1968  104409 104408  104408 104409         10440802
1969  104410 104408  104408 104410         10440802
1970  104447 104445  104445 104447         10444502

[1971 rows x 3 columns]

In [62]:
joined = mvmt_join_df.merge(mvmts, how='left')
# for some reason some uturns allowable per control.dat weren't included in the mvmts table.
# we'll drop them for now but note potential for ambiguity
joined[joined['ctrl_type'] != 'signal']

,ib_link_id,ob_link_id,timing_phase_id,mvmt_id,node_id,name,start_ib_lane,end_ib_lane,start_ob_lane,end_ob_lane,type,penalty,capacity,ctrl_type
896,101957 100092,100092 101957,10009202,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
924,100142 100115,100115 100142,10011503,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
925,100135 100115,100115 100135,10011503,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
951,100233 100176,100176 100233,10017601,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
952,100232 100176,100176 100232,10017601,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1966,100689 103812,103812 100689,10381201,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1967,100683 103812,103812 100683,10381202,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1968,104409 104408,104408 104409,10440802,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1969,104410 104408,104408 104410,10440802,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1970,104447 104445,104445 104447,10444502,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN

In [74]:
joined = mvmt_join_df.merge(mvmts, how='inner')
joined

,ib_link_id,ob_link_id,timing_phase_id,mvmt_id,node_id,name,start_ib_lane,end_ib_lane,start_ob_lane,end_ob_lane,type,penalty,capacity,ctrl_type
0,100001 100000,100000 100289,10000001,1016,100000,NaN,-1,-1,1,1,left,NaN,NaN,signal
1,100283 100000,100000 100001,10000001,1019,100000,NaN,1,1,1,1,thru,NaN,NaN,signal
2,100284 100000,100000 100001,10000002,1017,100000,NaN,1,1,1,1,left,NaN,NaN,signal
3,100000 100001,100001 101998,10000101,1023,100001,NaN,-1,-1,1,1,left,NaN,NaN,signal
4,100002 100001,100001 100000,10000101,1026,100001,NaN,1,1,1,1,thru,NaN,NaN,signal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,104410 104408,104408 100756,10440802,12494,104408,NaN,1,1,1,1,right,NaN,NaN,signal
1889,100565 104445,104445 104446,10444501,12610,104445,NaN,1,1,2,2,right,NaN,NaN,signal
1890,100564 104445,104445 104447,10444501,12609,104445,NaN,1,1,1,1,right,NaN,NaN,signal
1891,104447 104445,104445 100565,10444502,12612,104445,NaN,1,1,1,1,right,NaN,NaN,signal
1892,104446 104445,104445 100564,10444502,12611,104445,NaN,2,2,1,1,right,NaN,NaN,signal

In [75]:
# check for any movements at a signalized intersection that aren't in the above list
mvmts[(~mvmts['mvmt_id'].isin(joined['mvmt_id'])) & (mvmts['ctrl_type'] == 'signal')]

Empty DataFrame
Columns: [mvmt_id, node_id, name, ib_link_id, start_ib_lane, end_ib_lane, ob_link_id, start_ob_lane, end_ob_lane, type, penalty, capacity, ctrl_type]
Index: []

In [83]:
pd.options.mode.copy_on_write = True
signal_phase_mvmt = joined[['timing_phase_id', 'mvmt_id']]

empty_columns = ['link_id', 'protection']
for col in empty_columns:
    signal_phase_mvmt[col] = pd.Series()
    
signal_phase_mvmt.insert(0, 'signal_phase_mvmt_id', signal_phase_mvmt.index)
signal_phase_mvmt

      signal_phase_mvmt_id  timing_phase_id  mvmt_id link_id protection
0                        0         10000001     1016     NaN        NaN
1                        1         10000001     1019     NaN        NaN
2                        2         10000002     1017     NaN        NaN
3                        3         10000101     1023     NaN        NaN
4                        4         10000101     1026     NaN        NaN
...                    ...              ...      ...     ...        ...
1888                  1888         10440802    12494     NaN        NaN
1889                  1889         10444501    12610     NaN        NaN
1890                  1890         10444501    12609     NaN        NaN
1891                  1891         10444502    12612     NaN        NaN
1892                  1892         10444502    12611     NaN        NaN

[1893 rows x 5 columns]

In [84]:
signal_controllers.to_csv('../../../examples/Lima/GMNS/signal_controller.csv', index=False)
signal_timing_plans.to_csv('../../../examples/Lima/GMNS/signal_timing_plan.csv', index=False)
signal_timing_phase.to_csv('../../../examples/Lima/GMNS/signal_timing_phase.csv', index=False)
signal_phase_mvmt.to_csv('../../../examples/Lima/GMNS/signal_timing_mvmt.csv', index=False)